
const Lazy = () => {
	return (
		<div>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel aliquet lacus, ut interdum eros. Donec ut tincidunt felis. Curabitur imperdiet sodales lectus eu laoreet. Vestibulum in est eget elit tincidunt pellentesque eget sed dui. Morbi eget convallis urna. In hendrerit euismod tellus. Phasellus nec luctus dui, eget tempor arcu. Nullam quis volutpat magna, eu vulputate mi.

			Nam id justo a lectus commodo malesuada ut ac arcu. Mauris consectetur suscipit massa vel feugiat. Nunc gravida justo turpis, at consectetur libero ultrices nec. Cras mattis elit quis elit ultricies, sed sodales sapien ultricies. Aliquam et ante eget nulla eleifend rutrum sed non urna. Ut egestas ut justo ut luctus. Nunc elementum laoreet massa, ac dapibus metus pretium et. Nulla congue tempor augue eget tempor. Fusce ac condimentum massa. Vestibulum id justo at nunc convallis ultricies. Quisque luctus posuere turpis, at consectetur ipsum efficitur sed. Morbi accumsan volutpat augue, at mollis purus tristique sed.

			Etiam non imperdiet risus, ac pharetra ligula. Cras non nulla at risus aliquam sollicitudin. Duis libero eros, gravida dapibus iaculis vel, vehicula nec ligula. Proin eu lacinia nulla, imperdiet varius ipsum. Aliquam id congue felis. Fusce luctus massa in arcu tincidunt elementum. Proin eros ipsum, viverra eu vehicula et, tincidunt nec lacus. In placerat justo at risus ornare, sed ultrices elit scelerisque. Vivamus maximus ornare quam. Vestibulum et elit eu velit volutpat venenatis. Ut nec dictum velit. Quisque eleifend ipsum nulla, vitae faucibus est faucibus eu. Etiam vitae mattis dolor. Cras dolor mauris, posuere sit amet eleifend sit amet, convallis at enim. Maecenas elit leo, sollicitudin vitae nibh a, ultrices viverra ipsum.

			Pellentesque ultricies tortor at neque porta, eu facilisis neque semper. Suspendisse tortor enim, finibus at turpis vel, tempor efficitur tellus. Donec mi libero, interdum sit amet lacinia euismod, varius ac nibh. Aenean ut lobortis libero. Ut euismod sem in ex congue molestie. Duis id odio odio. Suspendisse maximus ipsum ut orci ullamcorper ullamcorper. Sed a consectetur augue. Sed sed eros ac libero semper vulputate a a purus. Etiam vitae lacus sed risus ullamcorper lobortis.

			Aenean rutrum lorem at enim hendrerit, id porttitor tortor feugiat. Nullam ac quam ultrices velit tempus mollis. Suspendisse non eleifend enim, ac commodo leo. Donec cursus venenatis lacinia. Donec varius blandit nulla, ut faucibus odio gravida vel. Cras eget arcu ante. Mauris tempor nisl non pharetra tincidunt. Suspendisse sit amet sapien in urna commodo aliquam. Sed gravida fermentum mi, nec pulvinar dolor rhoncus ac. Cras ultricies ac quam ut pellentesque. Ut elementum massa non tellus eleifend, sit amet lobortis tellus elementum. Aenean tristique nulla vel gravida rutrum. Aliquam eleifend quam at quam elementum dictum.

			Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut auctor sagittis sapien sed posuere. Cras blandit turpis tempus convallis ultrices. Pellentesque lacinia semper orci sit amet fermentum. Nulla aliquam ut enim a feugiat. Proin in ante pretium, vulputate orci id, egestas ligula. Pellentesque sed justo at erat dapibus placerat eu quis orci. In imperdiet ullamcorper pharetra.

			In auctor, nisi non finibus congue, eros arcu mattis est, in imperdiet diam magna sit amet metus. Nunc id ligula eleifend, tincidunt eros vitae, porta nunc. Aenean et nisi condimentum, faucibus nisi eu, finibus nunc. Donec bibendum neque eget leo congue congue. Nam rhoncus feugiat dignissim. Curabitur ornare imperdiet tincidunt. Aliquam volutpat ante id dignissim eleifend. Fusce semper bibendum luctus. Nulla rhoncus quam ac maximus pharetra.

			Quisque eu mollis enim. Fusce urna neque, aliquam imperdiet dui in, rhoncus lobortis magna. Duis quis nisl in velit eleifend iaculis. Praesent nec erat erat. Nulla auctor sed lectus eget faucibus. Quisque pretium tempor tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at ipsum sapien. Proin sed eros fringilla justo auctor malesuada venenatis id sem. Cras dapibus ligula vel laoreet malesuada. Nulla tempor, enim quis consequat hendrerit, mi turpis faucibus lacus, vitae viverra orci elit vitae tellus. Proin euismod magna mi, nec consequat lorem venenatis eu. Vivamus varius metus eu lorem congue, id laoreet tellus aliquam.

			Cras varius nisl eget ullamcorper feugiat. Nunc sodales a urna vitae euismod. Pellentesque leo magna, faucibus nec varius nec, porta sed eros. Nullam ac erat posuere, molestie metus ut, maximus ipsum. Aliquam finibus convallis leo vitae tempus. Integer ullamcorper ipsum semper vehicula sagittis. Sed sollicitudin sollicitudin turpis, sed venenatis urna laoreet nec. Mauris in mi eget felis varius volutpat eget auctor lacus.

			Nam euismod risus non nisl vulputate consectetur. Proin non tempus nunc. Morbi malesuada gravida condimentum. Fusce rhoncus eget orci id tempor. Sed ut felis consectetur, elementum erat et, iaculis ex. Fusce scelerisque est non lacus feugiat, et vehicula eros finibus. Nam quis gravida lectus.

			Aliquam ullamcorper est sagittis, consectetur neque vel, luctus sem. Sed condimentum id justo ac accumsan. Ut nec leo sit amet velit lobortis consequat non at elit. Nam egestas orci ac placerat accumsan. Curabitur ullamcorper dolor ac turpis vulputate, placerat consequat arcu aliquam. Nam vitae enim enim. Vestibulum hendrerit dolor ac velit vehicula porttitor. Donec facilisis dui nec magna tempor tempus nec id lorem. Vivamus ut congue nisl. Proin nulla est, iaculis sed interdum eget, posuere sit amet tortor.

			Proin ac velit tortor. Sed pharetra mauris sed erat tincidunt, sed auctor libero pretium. Proin at leo iaculis lectus porttitor sodales. Vestibulum feugiat ante non tincidunt mollis. In eu eros malesuada, iaculis mi in, porta elit. Donec eu ultricies ligula, in bibendum ex. Vestibulum eleifend massa et metus commodo eleifend ac at massa. Ut sed aliquam ex. Mauris ligula elit, sagittis at sodales vel, vulputate at sapien. Sed malesuada molestie gravida. Phasellus id ipsum ligula.

			Pellentesque eget lacus nulla. Sed accumsan dolor ac felis sodales, eget lacinia sapien consequat. Praesent ac eros vulputate, tempus mauris sed, iaculis urna. Fusce faucibus augue consectetur convallis rutrum. Aenean dictum massa et finibus tincidunt. Aliquam at mi eleifend, ornare dui vitae, imperdiet lacus. Mauris pulvinar dignissim elit, vitae porttitor metus lacinia ut. Sed posuere imperdiet urna, sit amet maximus nisl rutrum vel. Donec id lorem dictum, faucibus ipsum quis, vestibulum turpis. Vestibulum convallis auctor dictum. Maecenas sodales, urna sed lacinia mattis, ante justo posuere sem, in semper orci diam eget justo. Nulla ullamcorper lorem nisi, id pellentesque mi condimentum in.

			Vestibulum tincidunt mi non diam pulvinar, sollicitudin pulvinar velit fringilla. Praesent luctus suscipit est vel dapibus. Aenean sed gravida mauris. Aenean sed lorem risus. Cras imperdiet tincidunt mattis. Phasellus elementum, diam eget iaculis consequat, orci turpis pellentesque orci, nec malesuada nibh orci eu augue. In ut venenatis est. Pellentesque venenatis tristique dapibus. Integer et mollis odio.

			Ut ut condimentum ligula. Vivamus pellentesque suscipit libero et lacinia. Fusce et lorem neque. Aenean elementum tortor libero, in placerat lorem tristique id. Cras molestie ultrices mauris maximus faucibus. Quisque id lectus eget justo ultricies semper. Integer efficitur est quis ante vehicula, et elementum mi accumsan. Ut pretium, dolor a iaculis vulputate, eros neque auctor magna, vitae pretium odio arcu sit amet nisi.

			Morbi vitae ante at purus pharetra vulputate. In sit amet orci volutpat, vehicula enim nec, posuere ipsum. Cras quis dui porttitor urna condimentum scelerisque. Sed laoreet ullamcorper diam, eget ultrices tellus. Proin aliquam sapien pretium lacus laoreet convallis. Nunc fringilla nibh id nibh tempor vulputate. Duis volutpat dui tortor. Sed magna sem, lobortis id enim non, cursus dapibus tellus. Donec ipsum arcu, dapibus ut tempor sit amet, vehicula vel ex. Suspendisse semper mollis turpis at egestas. Praesent porta scelerisque lacus, egestas tincidunt augue posuere nec. Suspendisse semper lorem vel libero condimentum pharetra. Nulla vel condimentum neque, ac luctus quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam vitae sagittis ex.

			Nulla facilisi. Quisque at nibh vel leo tristique semper posuere eu velit. Proin dignissim nec urna non auctor. Integer gravida, leo nec lobortis luctus, ipsum justo gravida leo, ut facilisis mauris quam a ipsum. Pellentesque id nulla eu urna varius tristique vitae vitae ex. Suspendisse potenti. Suspendisse porttitor imperdiet nibh vitae placerat. In urna neque, scelerisque fermentum urna in, pretium feugiat erat. Curabitur rhoncus lacus at placerat tincidunt. Donec fringilla porttitor ligula, quis eleifend ligula vehicula sagittis. Nunc tempus justo et sagittis condimentum.

			Phasellus facilisis risus et massa ullamcorper, dapibus dictum dolor viverra. Pellentesque feugiat odio maximus interdum tempor. In elementum augue eu risus luctus blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin suscipit nec quam rhoncus maximus. Nulla facilisi. Maecenas et risus vulputate, malesuada enim eu, efficitur tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris commodo, leo nec malesuada mattis, velit dui ornare massa, vitae laoreet turpis diam sed ex.

			Vivamus erat urna, pretium ac justo id, sodales ullamcorper sem. Curabitur fringilla dolor id nibh imperdiet, at efficitur elit cursus. Cras sollicitudin magna libero, eu vehicula sem venenatis at. Vestibulum tincidunt mauris justo, non semper augue auctor maximus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin convallis pulvinar nunc quis semper. Aenean faucibus felis sit amet ipsum auctor tempor.

			Donec vitae vestibulum dolor. Vestibulum a nisi consequat, rhoncus diam a, bibendum nunc. Pellentesque vestibulum dictum sagittis. Vestibulum bibendum lorem in vestibulum aliquet. Nunc commodo dui eu lorem finibus mollis. Nunc malesuada, libero eu ultrices dignissim, dolor neque venenatis magna, non vehicula augue nisl semper orci. Duis eleifend mollis fringilla. Fusce lobortis risus ac fermentum blandit. Pellentesque faucibus enim vel auctor rutrum. Quisque auctor nisi at est egestas, sit amet pulvinar nisl imperdiet. Phasellus et lobortis ante.

			Sed leo eros, vehicula nec orci non, pharetra maximus ex. Quisque rhoncus aliquam condimentum. Nam id hendrerit metus. Phasellus sit amet luctus diam. Donec eu libero semper, volutpat tellus et, sodales metus. Donec suscipit odio eget faucibus lobortis. Integer efficitur, nunc id tincidunt molestie, augue sem pulvinar metus, vitae molestie velit nisi sed velit. Integer vestibulum ut quam id faucibus. Duis vestibulum lacus in quam viverra, ut convallis lorem varius. Pellentesque luctus rutrum dui finibus suscipit. Proin urna neque, lacinia eget mollis et, feugiat vel lectus. Nulla non lectus eget nunc rutrum interdum. Duis ultricies sodales tempus. Nunc lacinia sapien mollis commodo facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam placerat leo sit amet tortor fringilla cursus.

			Suspendisse id dolor et nibh porttitor congue eget at metus. Nunc fringilla mollis ligula, non suscipit purus iaculis id. Morbi nec neque laoreet, vehicula arcu nec, imperdiet urna. Cras malesuada sit amet nisi in rutrum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel fringilla lorem. Ut rutrum pellentesque nibh et accumsan. Aenean at velit tortor. Etiam maximus vitae augue nec pellentesque. Proin sodales urna sed gravida placerat. Sed faucibus non leo ac consequat. Duis ac arcu condimentum, varius augue nec, tincidunt nibh.

			Curabitur auctor risus justo, ut elementum ligula tempus id. Ut nec velit vel quam finibus dapibus quis id mi. Maecenas maximus molestie velit eget convallis. Suspendisse purus dolor, dapibus ut varius et, feugiat quis mauris. Aenean eu erat rhoncus, fermentum eros eu, vestibulum purus. Praesent sodales consequat enim, et sollicitudin odio porta quis. Morbi sit amet dolor accumsan, aliquam neque rutrum, faucibus dui. Praesent lorem purus, malesuada id lectus et, vulputate molestie tortor. Nunc id ornare elit. Phasellus vestibulum ipsum eget eros finibus rhoncus. Vivamus efficitur sit amet justo non consequat. Donec facilisis sed tellus ut aliquam. Vestibulum interdum velit sit amet lectus vestibulum, nec fermentum orci facilisis.

			Pellentesque porta mi ac fringilla hendrerit. Vivamus bibendum gravida convallis. Curabitur tristique ornare mi, in vehicula purus. Fusce non volutpat ipsum. Sed placerat vestibulum ligula, nec faucibus nisi rhoncus quis. Nunc non scelerisque urna. Sed id metus dui. Curabitur et dui feugiat, luctus ipsum eget, placerat est. Vestibulum mauris orci, pharetra a velit ut, ultrices maximus nunc. Duis a urna eu ante venenatis ultricies vitae a augue. Ut felis velit, dapibus a sapien at, suscipit tincidunt erat. Maecenas vel magna ut nunc pretium tempor sollicitudin nec tellus.

			Aenean nec lacus faucibus, eleifend nibh a, auctor ante. Donec mi dui, pretium luctus justo et, viverra rhoncus dolor. Donec efficitur purus ut ligula sollicitudin, ac tempor lacus elementum. Curabitur vel leo vel neque tincidunt hendrerit. Aliquam vitae dolor ex. Ut non orci bibendum, dignissim urna at, efficitur felis. Praesent vitae nulla a urna ullamcorper vestibulum. Nullam imperdiet, ante eget congue dictum, justo augue consequat velit, nec mollis ex tellus et elit. Donec nulla justo, pretium a ultricies nec, tincidunt vel felis. Aenean in varius turpis. Nam dictum erat orci, nec tincidunt diam convallis id. Fusce varius mollis consectetur. Donec facilisis sollicitudin turpis ac mollis.

			Vestibulum scelerisque consequat purus, ac pharetra orci semper ac. Fusce aliquam, magna consequat bibendum dapibus, lectus nulla bibendum sem, ac fermentum felis tellus a risus. Etiam in ex aliquet, mollis sem id, suscipit augue. Integer vel elit sed mi lobortis accumsan et ac velit. Pellentesque purus magna, volutpat finibus nulla suscipit, porta malesuada nisl. Ut est arcu, consequat efficitur nisi sit amet, lacinia semper dolor. Nullam ac leo non lorem scelerisque semper non eu massa. Nam commodo lacus arcu, non placerat odio scelerisque vitae. Sed tempor magna id magna semper, eget gravida purus consequat. Phasellus lacinia nunc elementum, volutpat dolor non, auctor tellus. Nullam a efficitur justo. Quisque lobortis odio non odio luctus aliquet. Ut accumsan risus massa, nec posuere neque bibendum eget. Sed eu felis id erat scelerisque finibus. Donec egestas magna eget nunc maximus ultrices nec id leo. Nam id diam pharetra, congue ligula id, pulvinar est.

			Mauris vehicula consectetur tortor, quis scelerisque lacus pretium nec. Suspendisse bibendum sollicitudin orci, sit amet ultricies eros. Morbi tincidunt facilisis varius. Aenean luctus, dui sodales aliquam condimentum, enim libero placerat elit, id ultrices justo sem sit amet velit. Phasellus mattis, nulla sed venenatis facilisis, arcu nulla aliquam felis, in dapibus ante metus vitae erat. Phasellus gravida lacus non odio porta, in laoreet lectus pulvinar. Duis a hendrerit velit, vel sollicitudin odio. Proin congue arcu in felis porttitor congue. Proin eget auctor augue, id rutrum tellus. Pellentesque cursus semper tincidunt. Duis id accumsan nibh, nec ultricies enim.

			Maecenas lobortis augue ligula, at ultrices nunc eleifend at. Integer volutpat ullamcorper tellus at dapibus. Etiam varius magna vehicula, efficitur orci vel, interdum nulla. Nulla elit ex, suscipit nec libero eu, gravida elementum urna. Nullam porttitor quam ut risus feugiat, vitae ornare purus posuere. In at sem vel erat consequat maximus sit amet non sapien. Aenean dictum lacinia volutpat.

			Proin rutrum, ante eget dignissim ornare, diam orci luctus libero, vitae sollicitudin magna purus vitae orci. Quisque ullamcorper facilisis dui, nec rutrum velit accumsan nec. Vivamus consectetur lacus arcu, vitae mollis eros euismod at. Nullam aliquam egestas leo, a blandit lectus sollicitudin in. Donec viverra euismod felis id tempor. Vivamus imperdiet non mi vel consequat. Vestibulum lobortis, mi et rhoncus tincidunt, lectus ipsum posuere nunc, ut luctus mi enim et arcu. Nulla facilisi. Suspendisse potenti.

			Sed commodo blandit erat id condimentum. In diam odio, elementum nec erat ornare, tincidunt mollis lorem. Vivamus in enim ac tellus tincidunt consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In pharetra erat vel tincidunt posuere. Etiam id ex et magna hendrerit porta. Fusce at turpis egestas, tempor ligula non, cursus metus. Integer scelerisque justo non tortor porttitor, ut lacinia arcu varius. Praesent turpis ipsum, dapibus vel placerat eget, rhoncus vel neque.
		</div>
	)
}

export default Lazy;